### ISSUE TITLE
WAVM support

### ISSUE THREAD

**Issue by lrettig** [ewasm/testnet#41] opened 2018-06-02 18:37 UTC
Investigate using WAVM for JIT compilation of ewasm

cf. https://github.com/ewasm/hera/issues/158

**Comment by lrettig** [comment] 2018-06-02 18:38
@jakelang's update from today's standup: Working on getting WABT + WAVM working together

**Comment by lrettig** [comment] 2018-06-06 21:05
@jakelang any updates here?

**Comment by jakelang** [comment] 2018-06-06 21:12
@lrettig abstraction layer is ready to go, just hoping that it gets merged before i start piling more on the PR.  also, this issue is a duplicate of ewasm/hera#158

**Comment by lrettig** [comment] 2018-06-08 19:56
@jakelang Thanks for the update. Yes I'm aware that it's a dupe, this repo is more of a high-level PM repo to track all of the testnet-critical tasks via Waffle with links to other tickets, as I added in the task description above.

**Comment by lrettig** [comment] 2018-06-08 20:54
@jakelang update from yesterday: figuring out WAVM’s runtime api right now, so i can use it in Hera. going to forget about the cmake stuff for now.

**Comment by lrettig** [comment] 2018-06-18 20:30
@jakelang update from Friday: still stuck trying to get WAVM to compile with cmake.

**Closed** 2018-08-28 01:34 UTC
Labels: in progress
